server:
  port: 8000
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio-service?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialet: org.hibernate.dialect.MySql8Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/cambio-service?useTimezone=true&serverTimezone=UTC
    user: root
    password: 1234
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: cambio-service/v3/api-docs